# modules/app-config/main.tf

terraform {
  required_version = ">= 1.14"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.7"
    }
  }
}

locals {
  # Build the full output directory path
  output_dir = "${var.base_dir}/${var.app_name}"

  # Merge caller-supplied tags with module-managed tags
  all_tags = merge(var.tags, {
    Module      = "app-config"
    AppName     = var.app_name
    Environment = var.environment
  })
}

# Main application config file
resource "local_file" "app_config" {
  filename        = "${local.output_dir}/app.conf"
  file_permission = "0644"
  content         = <<-EOT
    # Application Configuration
    # Managed by Terraform module: app-config
    # DO NOT EDIT MANUALLY
    
    app_name    = "${var.app_name}"
    environment = "${var.environment}"
    port        = ${var.port}
    log_level   = "${var.log_level}"
    debug       = ${var.debug_mode}
  EOT
}

# Environment-specific overrides file
resource "local_file" "env_overrides" {
  filename        = "${local.output_dir}/${var.environment}.conf"
  file_permission = "0644"
  content         = <<-EOT
    # Environment Overrides: ${var.environment}
    # Generated by Terraform module: app-config
    
    ${join("\n", [for k, v in var.env_overrides : "${k} = ${v}"])}
  EOT
}

# Tags/metadata file
resource "local_file" "metadata" {
  filename        = "${local.output_dir}/metadata.json"
  file_permission = "0644"
  content         = jsonencode(local.all_tags)
}
